import Head from 'next/head'
import styles from '../styles/Home.module.css';
import { Banner, Card } from '../components/index.components'
import Image from 'next/image'
import coffeeStores from '../data/coffee-stores.json'
/**
 * Discover-coffee-stores - version 1.15 -  Home page ( index js )
 * - Fetaures:
 * 
 *    --> Implementing 'getStatictProps' server rendering in order 
 *        to pre render images
 * 
 * Note: This styles are grid layout based thinking in mobile
 * first
*/


export async function getStaticProps(context) {
  
  return{
    props:{coffeeStores},// will be passed to the page component as props
  }
}

const handleOnBannerBtnClick = () => {
  console.log("hi banner button!!")
}

export default function Home(props) {
  
  console.log('coffeeStores pre render ==>', props)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffe Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick}/>
        <div className={styles.heroImage}>
          <Image src='/statics/hero_image.png' width={650} height={550}/>
        </div>
        <div className={styles.cardLayout}>
          {coffeeStores.map((coffeeStore) => {
            
            return(
              <Card 
                key={coffeeStore.id}
                className={styles.card}
                name={coffeeStore.name}
                imgUrl={coffeeStore.imgUrl}
                href={`/coffee-store/${coffeeStore.id}`}
              />
            )
          })}
        </div>
      </main>

    </div>
  )
}
